export { default as AdminLayout } from "./AdminLayout";
export { default as Home } from "./Home";
export { default as ManageCustomer } from "./ManageCustomer";
export { default as ManageOrder } from "./ManageOrder";
export { default as ManageProduct } from "./ManageProduct";
export { default as CreateProduct } from "./CreateProduct";
export { default as ManageUser } from "./ManageUser";
export { default as Supplier } from "./Supplier";
export { default as ManageNotification } from "./ManageNotification";
